"use client";

import { useEffect, useMemo, useState } from "react";

type Token={id:string;label:string;short:string;value?:number;kind:"account"|"operator"};
type Exercise={id:string;title:string;category:"operacion"|"inversion"|"financiamiento";direction:"ingreso"|"egreso";answer:string[];result:number};
type Scenario={name:string;description:string;scale:number;values:Record<string,number>};
const M=1_000_000;
const money=(n:number)=>new Intl.NumberFormat("es-CL",{style:"currency",currency:"CLP",maximumFractionDigits:0}).format(n);
const tokens:Token[]=[
 {id:"cash-i",label:"Efectivo inicial · $6.200.000",short:"Efectivo inicial",value:6.2*M,kind:"account"},{id:"cash-f",label:"Efectivo final · $16.000.000",short:"Efectivo final",value:16*M,kind:"account"},
 {id:"cli-i",label:"Clientes inicial · $8.600.000",short:"Clientes inicial",value:8.6*M,kind:"account"},{id:"cli-f",label:"Clientes final · $11.200.000",short:"Clientes final",value:11.2*M,kind:"account"},
 {id:"inv-i",label:"Inventario inicial · $13.400.000",short:"Inventario inicial",value:13.4*M,kind:"account"},{id:"inv-f",label:"Inventario final · $10.900.000",short:"Inventario final",value:10.9*M,kind:"account"},
 {id:"ppe-i",label:"PPE inicial · $35.000.000",short:"PPE inicial",value:35*M,kind:"account"},{id:"ppe-f",label:"PPE final · $41.000.000",short:"PPE final",value:41*M,kind:"account"},
 {id:"prov-i",label:"Proveedores inicial · $7.100.000",short:"Proveedores inicial",value:7.1*M,kind:"account"},{id:"prov-f",label:"Proveedores final · $9.000.000",short:"Proveedores final",value:9*M,kind:"account"},
 {id:"rem-i",label:"Remuneraciones inicial · $1.100.000",short:"Remuneraciones inicial",value:1.1*M,kind:"account"},{id:"rem-f",label:"Remuneraciones final · $700.000",short:"Remuneraciones final",value:.7*M,kind:"account"},
 {id:"prest-i",label:"Préstamos inicial · $12.000.000",short:"Préstamos inicial",value:12*M,kind:"account"},{id:"prest-f",label:"Préstamos final · $15.500.000",short:"Préstamos final",value:15.5*M,kind:"account"},
 {id:"ventas",label:"Ventas · $48.000.000",short:"Ventas",value:48*M,kind:"account"},{id:"cv",label:"Costo de ventas · $29.000.000",short:"Costo de ventas",value:29*M,kind:"account"},{id:"gasto-rem",label:"Gasto remuneraciones · $6.000.000",short:"Gasto remuneraciones",value:6*M,kind:"account"},{id:"dep",label:"Depreciación · $2.100.000",short:"Depreciación",value:2.1*M,kind:"account"},
 {id:"int-exp",label:"Gasto intereses · $1.200.000",short:"Gasto intereses",value:1.2*M,kind:"account"},{id:"int-i",label:"Intereses por pagar inicial · $300.000",short:"Intereses por pagar inicial",value:.3*M,kind:"account"},{id:"int-f",label:"Intereses por pagar final · $200.000",short:"Intereses por pagar final",value:.2*M,kind:"account"},
 {id:"tax-exp",label:"Gasto impuesto · $2.500.000",short:"Gasto impuesto",value:2.5*M,kind:"account"},{id:"tax-i",label:"Impuestos por pagar inicial · $800.000",short:"Impuestos por pagar inicial",value:.8*M,kind:"account"},{id:"tax-f",label:"Impuestos por pagar final · $1.000.000",short:"Impuestos por pagar final",value:1*M,kind:"account"},
 {id:"ins-exp",label:"Gasto seguros · $900.000",short:"Gasto seguros",value:.9*M,kind:"account"},{id:"pre-i",label:"Seguros anticipados inicial · $400.000",short:"Seguros anticipados inicial",value:.4*M,kind:"account"},{id:"pre-f",label:"Seguros anticipados final · $600.000",short:"Seguros anticipados final",value:.6*M,kind:"account"},
 {id:"other-exp",label:"Otros gastos operativos · $3.000.000",short:"Otros gastos operativos",value:3*M,kind:"account"},{id:"accr-i",label:"Otros pasivos inicial · $500.000",short:"Otros pasivos inicial",value:.5*M,kind:"account"},{id:"accr-f",label:"Otros pasivos final · $700.000",short:"Otros pasivos final",value:.7*M,kind:"account"},
 {id:"other-inc",label:"Otros ingresos · $1.400.000",short:"Otros ingresos",value:1.4*M,kind:"account"},{id:"orec-i",label:"Otras cuentas por cobrar inicial · $700.000",short:"Otras cuentas por cobrar inicial",value:.7*M,kind:"account"},{id:"orec-f",label:"Otras cuentas por cobrar final · $900.000",short:"Otras cuentas por cobrar final",value:.9*M,kind:"account"},
 {id:"cap-i",label:"Capital inicial · $30.000.000",short:"Capital inicial",value:30*M,kind:"account"},{id:"cap-f",label:"Capital final · $32.000.000",short:"Capital final",value:32*M,kind:"account"},{id:"re-i",label:"Resultados acumulados inicial · $13.000.000",short:"Resultados acumulados inicial",value:13*M,kind:"account"},{id:"re-f",label:"Resultados acumulados final · $15.800.000",short:"Resultados acumulados final",value:15.8*M,kind:"account"},{id:"profit",label:"Utilidad del ejercicio · $4.800.000",short:"Utilidad del ejercicio",value:4.8*M,kind:"account"},
 {id:"ppe-book",label:"Valor libro PPE vendido · $1.800.000",short:"Valor libro PPE vendido",value:1.8*M,kind:"account"},{id:"ppe-gain",label:"Ganancia venta PPE · $600.000",short:"Ganancia venta PPE",value:.6*M,kind:"account"},{id:"new-loan",label:"Nuevos préstamos · $6.500.000",short:"Nuevos préstamos",value:6.5*M,kind:"account"},
 {id:"invest-i",label:"Inversiones inicial · $4.000.000",short:"Inversiones inicial",value:4*M,kind:"account"},{id:"invest-f",label:"Inversiones final · $5.500.000",short:"Inversiones final",value:5.5*M,kind:"account"},{id:"invest-book",label:"Valor libro inversión vendida · $1.000.000",short:"Valor libro inversión vendida",value:1*M,kind:"account"},{id:"invest-gain",label:"Ganancia venta inversión · $200.000",short:"Ganancia venta inversión",value:.2*M,kind:"account"},
 {id:"lease-i",label:"Pasivo leasing inicial · $4.000.000",short:"Pasivo leasing inicial",value:4*M,kind:"account"},{id:"lease-f",label:"Pasivo leasing final · $3.800.000",short:"Pasivo leasing final",value:3.8*M,kind:"account"},{id:"new-lease",label:"Nuevo leasing · $1.000.000",short:"Nuevo leasing",value:1*M,kind:"account"},
 {id:"interest-inc",label:"Ingreso por intereses · $1.000.000",short:"Ingreso por intereses",value:1*M,kind:"account"},{id:"intrec-i",label:"Intereses por cobrar inicial · $400.000",short:"Intereses por cobrar inicial",value:.4*M,kind:"account"},{id:"intrec-f",label:"Intereses por cobrar final · $300.000",short:"Intereses por cobrar final",value:.3*M,kind:"account"},{id:"div-inc",label:"Ingreso por dividendos · $800.000",short:"Ingreso por dividendos",value:.8*M,kind:"account"},{id:"divrec-i",label:"Dividendos por cobrar inicial · $200.000",short:"Dividendos por cobrar inicial",value:.2*M,kind:"account"},{id:"divrec-f",label:"Dividendos por cobrar final · $100.000",short:"Dividendos por cobrar final",value:.1*M,kind:"account"},{id:"ppe-total",label:"Adquisiciones PPE totales · $8.100.000",short:"Adquisiciones PPE totales",value:8.1*M,kind:"account"},{id:"ppe-credit",label:"PPE adquirido a crédito · $1.500.000",short:"PPE adquirido a crédito",value:1.5*M,kind:"account"},
 {id:"plus",label:"+",short:"+",kind:"operator"},{id:"minus",label:"−",short:"−",kind:"operator"}
];
const exercises:Exercise[]=[
 {id:"clientes",title:"Cobrado a clientes",category:"operacion",direction:"ingreso",answer:["ventas","plus","cli-i","minus","cli-f"],result:45.4*M},
 {id:"proveedores",title:"Pagado a proveedores",category:"operacion",direction:"egreso",answer:["cv","plus","inv-f","minus","inv-i","plus","prov-i","minus","prov-f"],result:24.6*M},
 {id:"remuneraciones",title:"Pagado por remuneraciones",category:"operacion",direction:"egreso",answer:["gasto-rem","plus","rem-i","minus","rem-f"],result:6.4*M},
 {id:"ppe",title:"Compra de propiedades, planta y equipo",category:"inversion",direction:"egreso",answer:["ppe-f","minus","ppe-i","plus","dep"],result:8.1*M},
 {id:"prestamos",title:"Préstamos bancarios recibidos",category:"financiamiento",direction:"ingreso",answer:["prest-f","minus","prest-i"],result:3.5*M}
 ,{id:"intereses",title:"Intereses pagados",category:"operacion",direction:"egreso",answer:["int-exp","plus","int-i","minus","int-f"],result:1.3*M}
 ,{id:"impuestos",title:"Impuestos pagados",category:"operacion",direction:"egreso",answer:["tax-exp","plus","tax-i","minus","tax-f"],result:2.3*M}
 ,{id:"seguros",title:"Seguros pagados",category:"operacion",direction:"egreso",answer:["ins-exp","plus","pre-f","minus","pre-i"],result:1.1*M}
 ,{id:"otros-pagos",title:"Otros pagos operacionales",category:"operacion",direction:"egreso",answer:["other-exp","plus","accr-i","minus","accr-f"],result:2.8*M}
 ,{id:"otros-cobros",title:"Otros cobros operacionales",category:"operacion",direction:"ingreso",answer:["other-inc","plus","orec-i","minus","orec-f"],result:1.2*M}
 ,{id:"capital",title:"Aportes de capital cobrados",category:"financiamiento",direction:"ingreso",answer:["cap-f","minus","cap-i"],result:2*M}
 ,{id:"dividendos-pagados",title:"Dividendos pagados",category:"financiamiento",direction:"egreso",answer:["re-i","plus","profit","minus","re-f"],result:2*M}
 ,{id:"venta-ppe",title:"Cobrado por venta de PPE",category:"inversion",direction:"ingreso",answer:["ppe-book","plus","ppe-gain"],result:2.4*M}
 ,{id:"pago-prestamo",title:"Pago de capital de préstamos",category:"financiamiento",direction:"egreso",answer:["prest-i","plus","new-loan","minus","prest-f"],result:3*M}
 ,{id:"compra-inversion",title:"Compra de inversiones",category:"inversion",direction:"egreso",answer:["invest-f","minus","invest-i","plus","invest-book"],result:2.5*M}
 ,{id:"venta-inversion",title:"Cobrado por venta de inversiones",category:"inversion",direction:"ingreso",answer:["invest-book","plus","invest-gain"],result:1.2*M}
 ,{id:"leasing",title:"Pago de capital de leasing",category:"financiamiento",direction:"egreso",answer:["lease-i","plus","new-lease","minus","lease-f"],result:1.2*M}
 ,{id:"intereses-cobrados",title:"Intereses cobrados",category:"operacion",direction:"ingreso",answer:["interest-inc","plus","intrec-i","minus","intrec-f"],result:1.1*M}
 ,{id:"dividendos-cobrados",title:"Dividendos cobrados",category:"operacion",direction:"ingreso",answer:["div-inc","plus","divrec-i","minus","divrec-f"],result:.9*M}
 ,{id:"ppe-efectivo",title:"PPE adquirido y pagado en efectivo",category:"inversion",direction:"egreso",answer:["ppe-total","minus","ppe-credit"],result:6.6*M}
];
const scenarios:Scenario[]=[
 {name:"Expansión comercial",description:"Las ventas crecen, aumentan las cuentas por cobrar y disminuyen los inventarios.",scale:1,values:{}},
 {name:"Cobranza intensiva",description:"La empresa reduce fuertemente sus cuentas por cobrar y recompone inventarios.",scale:1,values:{"cli-i":11.8*M,"cli-f":8.4*M,"inv-i":9.7*M,"inv-f":14.2*M,"prov-i":9.6*M,"prov-f":8.1*M,"cash-i":7.4*M}},
 {name:"Desendeudamiento",description:"Se reciben pocos préstamos nuevos y se amortiza una parte importante de la deuda.",scale:1,values:{"prest-i":18*M,"prest-f":12*M,"new-loan":2*M,"lease-i":5.2*M,"lease-f":2.9*M,"new-lease":.4*M,"cash-i":9.1*M}},
 {name:"Inversión productiva",description:"La empresa compra PPE, una parte a crédito, y vende un activo antiguo con pérdida.",scale:1,values:{"ppe-i":32*M,"ppe-f":44*M,"dep":2.8*M,"ppe-total":16.6*M,"ppe-credit":4.2*M,"ppe-book":2.5*M,"ppe-gain":-.3*M,"cash-i":8*M}},
 {name:"Capital de trabajo exigente",description:"Suben inventarios y clientes; proveedores y remuneraciones por pagar disminuyen.",scale:1,values:{"cli-i":7.9*M,"cli-f":13.6*M,"inv-i":10.2*M,"inv-f":16.4*M,"prov-i":10.5*M,"prov-f":6.8*M,"rem-i":1.5*M,"rem-f":.4*M,"cash-i":12*M}},
 {name:"Rotación de inversiones",description:"Se venden inversiones con ganancia, se adquieren otras y se distribuyen dividendos.",scale:1,values:{"invest-i":6.5*M,"invest-f":3.8*M,"invest-book":4.1*M,"invest-gain":.7*M,"re-i":16*M,"re-f":17.1*M,"profit":4.8*M,"cash-i":6.7*M}},
 {name:"Caso de menor escala",description:"Una empresa más pequeña presenta relaciones contables distintas, no una copia proporcional.",scale:.72,values:{"cli-i":5.4*M,"cli-f":7.9*M,"inv-i":11.1*M,"inv-f":8.3*M,"prov-i":4.8*M,"prov-f":6.9*M,"prest-i":8.2*M,"prest-f":10.1*M,"new-loan":3.6*M,"cash-i":4.9*M}},
 {name:"Caso de mayor escala",description:"Una empresa de mayor tamaño combina cobros, inversión y financiamiento diferentes.",scale:1.35,values:{"cli-i":14.2*M,"cli-f":12.1*M,"inv-i":16.8*M,"inv-f":20.4*M,"prov-i":11.7*M,"prov-f":14.9*M,"prest-i":22*M,"prest-f":25.6*M,"new-loan":8.4*M,"cash-i":13.5*M}}
];
const find=(id:string|null)=>tokens.find(t=>t.id===id);
const evaluateFormula=(answer:string[],valueOf:(id:string)=>number)=>{let total=0;let sign=1;for(const id of answer){if(id==="plus")sign=1;else if(id==="minus")sign=-1;else total+=sign*valueOf(id)}return Math.abs(total)};

function SourceCell({id,valueOf}:{id:string;valueOf:(id:string)=>number}){return <button className="source-value" draggable onDragStart={e=>e.dataTransfer.setData("text/plain",id)} title="Arrastrar al cálculo">{money(valueOf(id))}<span>⋮⋮</span></button>}

function Builder({exercise,index,valueOf,onSave}:{exercise:Exercise;index:number;valueOf:(id:string)=>number;onSave:(ok:boolean)=>void}){
 const [placed,setPlaced]=useState<(string|null)[]>(Array(exercise.answer.length).fill(null));const [saved,setSaved]=useState(false);
 const correct=placed.every((x,i)=>x===exercise.answer[i]);
 const place=(id:string,at?:number)=>{if(saved)return;setPlaced(p=>{const pos=at??p.findIndex(x=>x===null);if(pos<0)return p;const n=[...p];n[pos]=id;return n})};
 const remove=(i:number)=>{if(!saved)setPlaced(p=>p.map((x,j)=>i===j?null:x))};
 return <article className={`builder ${saved?"saved":""}`}><div className="builder-title"><span>{String(index+1).padStart(2,"0")}</span><div><small>{exercise.category} · {exercise.direction}</small><h3>{exercise.title}</h3></div>{saved&&<b>✓ Respuesta guardada</b>}</div><div className="operator-tray"><span>AGREGA EL OPERADOR</span><button disabled={saved} onClick={()=>place("plus")}>+</button><button disabled={saved} onClick={()=>place("minus")}>−</button></div><div className="drop-formula">{placed.map((id,i)=>{const t=find(id);return <div key={i} className={`drop-slot ${t?.kind||""}`} onDragOver={e=>e.preventDefault()} onDrop={e=>{e.preventDefault();place(e.dataTransfer.getData("text/plain"),i)}} onClick={()=>remove(i)}>{t?<><b>{t.short}</b>{t.value!==undefined&&<small>{money(valueOf(id))}</small>}</>:<span>Arrastra una cuenta<br/>o agrega un signo</span>}</div>})}<i>=</i><div className="unknown">$ ?</div></div><p className="instruction">Arrastra los valores directamente desde los estados financieros de la izquierda.</p><button className="save-answer" disabled={saved||placed.some(x=>!x)} onClick={()=>{setSaved(true);onSave(correct)}}>{saved?"Respuesta enviada":"Guardar respuesta"}</button>{saved&&<div className={`reveal ${correct?"right":"wrong"}`}><div><small>CÁLCULO CORRECTO</small><strong>{exercise.answer.map(id=>find(id)?.short).join("  ")} = {money(exercise.result)}</strong></div><span>{correct?"Tu construcción era correcta.":"Tu respuesta quedó guardada. Compara con esta solución."}</span></div>}</article>
}

export default function Home(){const [view,setView]=useState<"inicio"|"actividad">("inicio");const [name,setName]=useState("");const [email,setEmail]=useState("");const [code,setCode]=useState("");const [consent,setConsent]=useState(false);const [codeSent,setCodeSent]=useState(false);const [authMessage,setAuthMessage]=useState("");const [authBusy,setAuthBusy]=useState(false);const [level,setLevel]=useState<1|2|3>(1);const [caseNo,setCaseNo]=useState(0);const [saved,setSaved]=useState<Record<string,boolean>>({});const [correct,setCorrect]=useState<Record<string,boolean>>({});const [remaining,setRemaining]=useState(1800);const [resultSent,setResultSent]=useState(false);const scenario=scenarios[caseNo%scenarios.length];const rawValue=(id:string)=>scenario.values[id]??(find(id)?.value||0)*scenario.scale;const baseExercises=exercises.slice(0,level===1?8:level===2?12:20);const activeExercises=baseExercises.map(e=>({...e,result:evaluateFormula(e.answer,rawValue)}));const fullChange=activeExercises.reduce((s,e)=>s+(e.direction==="egreso"?-e.result:e.result),0);const endingCash=rawValue("cash-i")+fullChange;const valueOf=(id:string)=>id==="cash-f"?endingCash:rawValue(id);const score=useMemo(()=>Math.round(Object.values(correct).filter(Boolean).length/activeExercises.length*100),[correct,activeExercises.length]);const completed=Object.keys(saved).length;const change=activeExercises.filter(e=>saved[e.id]).reduce((s,e)=>s+(e.direction==="egreso"?-e.result:e.result),0);const reset=(nextLevel:1|2|3=level)=>{setLevel(nextLevel);setSaved({});setCorrect({});setCaseNo(n=>n+1);setRemaining(1800);setResultSent(false)};const basicIds=["int-exp","int-i","int-f","tax-exp","tax-i","tax-f","ins-exp","pre-i","pre-f"];const intermediateIds=[...basicIds,"other-exp","accr-i","accr-f","other-inc","orec-i","orec-f","cap-i","cap-f","re-i","re-f","profit"];const advancedIds=[...intermediateIds,"ppe-book","ppe-gain","new-loan","invest-i","invest-f","invest-book","invest-gain","lease-i","lease-f","new-lease","interest-inc","intrec-i","intrec-f","div-inc","divrec-i","divrec-f","ppe-total","ppe-credit"];const noteIds=level===1?basicIds:level===2?intermediateIds:advancedIds;
 useEffect(()=>{if(view!=="actividad"||remaining<=0||completed===activeExercises.length)return;const timer=setInterval(()=>setRemaining(v=>Math.max(0,v-1)),1000);return()=>clearInterval(timer)},[view,remaining,completed,activeExercises.length]);
 const requestCode=async()=>{setAuthBusy(true);setAuthMessage("");const r=await fetch("/api/auth/request-code",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({name,email,consent})});const d=await r.json().catch(()=>({}));setAuthBusy(false);if(r.ok){setCodeSent(true);setAuthMessage("Código enviado. Revisa tu correo institucional.")}else setAuthMessage(d.error||"No fue posible enviar el código.")};
 const verifyCode=async()=>{setAuthBusy(true);setAuthMessage("");const r=await fetch("/api/auth/verify-code",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({email,code})});const d=await r.json().catch(()=>({}));setAuthBusy(false);if(r.ok)setView("actividad");else setAuthMessage(d.error||"No fue posible verificar el código.")};
 return <main><header><div className="brand"><span>ƒ</span><div><strong>FlujoLab</strong><small>Construcción desde estados financieros</small></div></div><nav><button className={view==="inicio"?"active":""} onClick={()=>setView("inicio")}>Inicio</button><button className={view==="actividad"?"active":""} onClick={()=>setView("actividad")}>Actividad</button></nav></header>
 {view==="inicio"&&<section className="hero"><span className="eyebrow">CONTABILIDAD II · APRENDER HACIENDO</span><h1>Arrastra desde los estados.<br/><em>Construye el efectivo.</em></h1><p>Cada intento combina un escenario contable distinto. Para proteger tus resultados, el acceso se valida mediante un código enviado al correo institucional.</p><div className="login">{!codeSent?<><label>Nombre completo<input maxLength={100} autoComplete="name" value={name} onChange={e=>setName(e.target.value)} placeholder="Nombre del alumno"/></label><label>Correo institucional<input maxLength={160} autoComplete="email" value={email} onChange={e=>setEmail(e.target.value)} placeholder="nombre@udd.cl o @mail.udp.cl"/></label><label className="consent"><input type="checkbox" checked={consent} onChange={e=>setConsent(e.target.checked)}/><span>Acepto que se utilicen mi nombre, correo y resultados exclusivamente para gestionar esta actividad académica y su seguimiento docente.</span></label><button disabled={authBusy||name.trim().length<3||!/^[^\s@]+@(udd\.cl|mail\.udp\.cl)$/i.test(email)||!consent} onClick={requestCode}>{authBusy?"Enviando…":"Enviar código →"}</button></>:<><div className="code-copy"><b>Código de seguridad</b><span>Enviado a {email}. Expira en 10 minutos.</span></div><label>Código de 6 dígitos<input inputMode="numeric" autoComplete="one-time-code" maxLength={6} value={code} onChange={e=>setCode(e.target.value.replace(/\D/g,""))} placeholder="000000"/></label><button disabled={authBusy||code.length!==6} onClick={verifyCode}>{authBusy?"Verificando…":"Verificar e ingresar →"}</button><button className="secondary" onClick={()=>{setCodeSent(false);setCode("");setAuthMessage("")}}>Cambiar correo</button></>}{authMessage&&<p className="auth-message" role="status">{authMessage}</p>}</div><div className="privacy-note"><b>Protección de datos</b><span>Código de un solo uso · sesión segura · máximo 3 intentos · datos visibles solo para el profesor.</span></div></section>}
 {view==="actividad"&&<section className="activity"><div className="activity-head"><div><span className="eyebrow">DESAFÍO PRÁCTICO · CASO {caseNo+1}</span><h1>{scenario.name}</h1><p>{scenario.description}</p></div><div className="score"><small>GUARDADAS</small><strong>{completed}/{activeExercises.length}</strong><span>{score}% correctas</span></div></div><div className="levelbar"><div><span>NIVEL DE DIFICULTAD</span><button className={level===1?"selected":""} onClick={()=>reset(1)}>1 · Básico</button><button className={level===2?"selected":""} onClick={()=>reset(2)}>2 · Intermedio</button><button className={level===3?"selected":""} onClick={()=>reset(3)}>3 · Avanzado</button></div><button className="newcase" onClick={()=>reset(level)}>↻ Generar nuevo caso</button></div><div className="learning-grid">
 <aside className="source-panel"><div className="panel-label">ORIGEN DE LOS DATOS</div><h2>Estados financieros</h2><p className="drag-note">Arrastra el monto que necesites desde cada celda.</p><section className="statement"><div className="statement-head"><b>Balance comparativo</b><span>CLP</span></div><table><thead><tr><th>Cuenta</th><th>2025</th><th>2026</th></tr></thead><tbody><tr><td>Efectivo</td><td><SourceCell id="cash-i" valueOf={valueOf}/></td><td><SourceCell id="cash-f" valueOf={valueOf}/></td></tr><tr><td>Clientes</td><td><SourceCell id="cli-i" valueOf={valueOf}/></td><td><SourceCell id="cli-f" valueOf={valueOf}/></td></tr><tr><td>Inventarios</td><td><SourceCell id="inv-i" valueOf={valueOf}/></td><td><SourceCell id="inv-f" valueOf={valueOf}/></td></tr><tr><td>PPE</td><td><SourceCell id="ppe-i" valueOf={valueOf}/></td><td><SourceCell id="ppe-f" valueOf={valueOf}/></td></tr><tr><td>Proveedores</td><td><SourceCell id="prov-i" valueOf={valueOf}/></td><td><SourceCell id="prov-f" valueOf={valueOf}/></td></tr><tr><td>Remun. por pagar</td><td><SourceCell id="rem-i" valueOf={valueOf}/></td><td><SourceCell id="rem-f" valueOf={valueOf}/></td></tr><tr><td>Préstamos</td><td><SourceCell id="prest-i" valueOf={valueOf}/></td><td><SourceCell id="prest-f" valueOf={valueOf}/></td></tr></tbody></table></section><section className="statement"><div className="statement-head"><b>Estado de Resultados</b><span>2026</span></div><table><tbody><tr><td>Ventas</td><td><SourceCell id="ventas" valueOf={valueOf}/></td></tr><tr><td>Costo de ventas</td><td><SourceCell id="cv" valueOf={valueOf}/></td></tr><tr><td>Gasto remuneraciones</td><td><SourceCell id="gasto-rem" valueOf={valueOf}/></td></tr><tr><td>Depreciación</td><td><SourceCell id="dep" valueOf={valueOf}/></td></tr><tr className="total"><td>Utilidad</td><td>{money(valueOf("profit"))}</td></tr></tbody></table></section><section className="notes"><div className="statement-head"><b>Notas adicionales</b><span>Nivel {level}</span></div><ul><li>La depreciación del período está incluida en los gastos y no representa salida de efectivo.</li>{level>=2&&<li>Revisa las notas: puede existir venta de PPE, adquisición a crédito o pago de deuda.</li>}{level>=2&&<li>Las variaciones de préstamos no siempre representan nuevos créditos.</li>}{level===3&&<li>Debes distinguir datos relevantes, transacciones sin efectivo y distractores.</li>}{level===3&&<li>Las cifras del caso concilian con el efectivo final del Balance.</li>}</ul></section><section className="statement note-values"><div className="statement-head"><b>Detalle de cuentas y notas</b><span>Arrastrables</span></div><table><tbody>{noteIds.map(id=><tr key={id}><td>{find(id)?.short}</td><td><SourceCell id={id} valueOf={valueOf}/></td></tr>)}</tbody></table></section></aside>
 <div className="questions">{activeExercises.map((e,i)=><Builder key={`${caseNo}-${level}-${e.id}`} exercise={e} valueOf={valueOf} index={i} onSave={async ok=>{setSaved(s=>({...s,[e.id]:true}));setCorrect(s=>({...s,[e.id]:ok}));await fetch("/api/progress",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({scenario:scenario.name,level,exerciseId:e.id,correct:ok,remainingSeconds:remaining})}).catch(()=>setAuthMessage("La respuesta quedó en pantalla, pero no se pudo guardar en el servidor."));if(completed+1===activeExercises.length&&!resultSent){setResultSent(true);fetch("/api/results",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({remainingSeconds:remaining,scenario:scenario.name,level})}).then(async r=>{if(!r.ok){const d=await r.json().catch(()=>({}));setAuthMessage(d.error||"No fue posible guardar el resultado.")}})}}}/>)}</div>
 <aside className="flow-panel"><div className="panel-label">RESULTADO ACUMULADO</div><h2>Estado de Flujo de Efectivo</h2><p>Tiempo: {String(Math.floor(remaining/60)).padStart(2,"0")}:{String(remaining%60).padStart(2,"0")} · El resultado se guarda al completar.</p>{(["operacion","inversion","financiamiento"] as const).map(cat=><section key={cat}><h3>Flujos de {cat}</h3>{activeExercises.filter(e=>e.category===cat).map(e=><div className={saved[e.id]?"shown":"empty"} key={e.id}><span>{e.title}</span><b>{saved[e.id]?(e.direction==="egreso"?`(${money(e.result)})`:money(e.result)):"—"}</b></div>)}</section>)}<div className="cash-check"><div><span>Variación construida</span><b>{money(change)}</b></div><div><span>Efectivo inicial</span><b>{money(valueOf("cash-i"))}</b></div><div className="ending"><span>Efectivo final calculado</span><b>{money(valueOf("cash-i")+change)}</b></div><div className={completed===activeExercises.length?"target ok":"target"}><span>Efectivo final del Balance</span><b>{money(endingCash)}</b></div></div>{completed===activeExercises.length&&<div className="result-confirm">✓ Resultado guardado para el profesor</div>}</aside>
 </div></section>}<footer>FlujoLab · Contabilidad II · Profesor Miguel Brengi <span>Versión 4.0 · Acceso seguro y casos variables</span></footer></main>}
